### ISSUE TITLE
"NaN" result in the null game

### ISSUE THREAD

**Issue by tallforasmurf** [0xf00ff00f/rotator#1]
If you tap to start, and then let the timer run without making any choices, after two minutes it tells you "NaN seconds per shape". Better to just leave off the second line of the message when "0 shapes rotated".

**Comment by 0xf00ff00f** [comment]
Yeah, the NaN is there on purpose:

https://github.com/0xf00ff00f/rotator/blob/master/demo.cc#L419

I'll replace it with an infinity symbol. :)

**Comment by tallforasmurf** [comment]
To a programmer it looks like it divided by 0 (pairs) and didn't catch the exception. So, yeah.

**Comment by 0xf00ff00f** [comment]
Removed the NaN when there are no matches, thanks. (Also replaced the time average with accuracy, which is a better stat.)
