### ISSUE TITLE
Game sometimes presents multiple valid pairs

### ISSUE THREAD

**Issue by elgertam** [0xf00ff00f/rotator#2]
I was presented this board, but the game didn't recognize the two highlighted shapes as equivalent; instead, the game was looking for the top-right, bottom-left pair. That pair was much trickier to see due to occlusion.

![image](https://user-images.githubusercontent.com/1118015/154912541-025b69a6-7f0f-4518-aee7-a7e83fce5d84.png)

Also, because occlusion is a tricky problem, would it be possible to give the shapes a trendy bit of springiness so we can drag them side to side or up & down to get a better view? If the springiness is set very stiff, the time to reorient the shape will cost the user more time any discernible gain they would get from seeing more of the shape other than in the case of occlusion.

**Comment by 0xf00ff00f** [comment]
Ouch. This should be fixed now (turns out that comparing floating point numbers for equality with == is a bad idea in general). Thank you so much for reporting!

I agree that occlusion is a problem. I like the idea of allowing the user to rotate the shapes a bit. Thanks!
