### ISSUE TITLE
Instructions on how to compile locally

### ISSUE THREAD

**Issue by Andrew-Pynch** [0xf00ff00f/rotator#3]
Greetings, 

I am dumb and don't know how to get this working locally since I have limited familiarity with C, and CPP. I know this is a fun side project you did on a throwaway account, but if possible would you consider providing some instructions on how to run this locally? Want to play around with this and add a couple of features for a personal version :-)

Either way, thanks for making this. Very cool project

**Comment by 0xf00ff00f** [comment]
Hey, just added some build instructions. Please let me know if it works for you!

**Comment by Andrew-Pynch** [comment]
Got it working by the way! Thanks for making these instructions
