### ISSUE TITLE
It generated a set that had no matching pair

### ISSUE THREAD

**Issue by adrianbienias** [0xf00ff00f/rotator#4]
![Screenshot from 2022-02-28 09-41-26](https://user-images.githubusercontent.com/25237195/155951994-c9ec4f74-8471-432f-b22b-6845c86d1513.png)

**Comment by 0xf00ff00f** [comment]
Thanks for the report. The matching pair could be the two leftmost shapes in the bottom row. When the time is up it should fade out all the shapes except for the matching pair, did it show anything?

**Comment by adrianbienias** [comment]
Can't tell. I was so sure there's no matching pair that I took a screenshot and posted it here. But now I see you're right. Some blocks are hidden where I thought there aren't any pieces. Thanks for the hint!

**Comment by 0xf00ff00f** [comment]
There's definitely an issue with blocks getting hidden. I'll try to change it to a parallel projection to see if it improves things. Thanks again.
